# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, mosaicoLib }:

cabal.mkDerivation (self: {
  pname = "mosaico-bin";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ mosaicoLib ];
  meta = {
    homepage = "http://ldc.usb.ve/~05-38235/cursos/CI3661/2015AJ/";
    description = "Generación interactiva de mosaicos (ejecutable)";
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
